version: "3.9"
services:
  app:
    build: .
    volumes:
      - .:/django
    ports:
      - 8000:8000
    environment:
      - POSTGRES_NAME=store_apis_db
      - POSTGRES_USER=bit68
      - POSTGRES_PASSWORD=postgres
      - SECRET_KEY=django-insecure-g^7y5fqdzejklzqlk_xhte5ve9(83dw1=t!x0=16&_^+k(u!m3
    image: app:django
    container_name: django_app_container
    command: python manage.py runserver 0.0.0.0:8000
    depends_on:
      - db 
  
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=store_apis_db
      - POSTGRES_USER=bit68
      - POSTGRES_PASSWORD=postgres
    container_name: bit68_postgres_db